"""
ui/css/style_loader.py
Helper untuk load file .qss + register Qt Resource otomatis.
Tidak butuh pyrcc6 — compile resource langsung via Python.

Cara pakai:
    from ui.css.style_loader import load_style
    app.setStyleSheet(load_style("darkstyle"))
"""

import os
import sys


_CSS_DIR = os.path.dirname(os.path.abspath(__file__))


def _compile_and_register_qrc(theme: str):
    """
    Compile .qrc → _rc.py menggunakan PyQt6.pyrcc (built-in),
    lalu import agar resource terdaftar ke Qt.
    Skip jika _rc.py sudah up-to-date.
    """
    theme_dir = os.path.join(_CSS_DIR, theme)
    qrc_file  = os.path.join(theme_dir, f"{theme}.qrc")
    rc_file   = os.path.join(theme_dir, f"{theme}_rc.py")

    if not os.path.isfile(qrc_file):
        return  # tidak ada .qrc, skip

    # Compile hanya jika _rc.py belum ada atau .qrc lebih baru
    need_compile = (
        not os.path.isfile(rc_file) or
        os.path.getmtime(qrc_file) > os.path.getmtime(rc_file)
    )

    if need_compile:
        try:
            from PyQt6.pyrcc import processResourceFile
            processResourceFile([qrc_file], rc_file, False)
            print(f"[style_loader] ✔ Compiled {theme}.qrc → {theme}_rc.py")
        except ImportError:
            # PyQt6.pyrcc tidak tersedia, coba cara alternatif
            _compile_qrc_manual(qrc_file, rc_file, theme)

    # Register resource ke Qt
    _import_rc(theme, theme_dir)


def _compile_qrc_manual(qrc_file: str, rc_file: str, theme: str):
    """
    Fallback: parse .qrc dan embed file PNG sebagai base64 ke _rc.py,
    lalu register ke Qt menggunakan QResource.
    Tidak butuh tool eksternal sama sekali.
    """
    import base64
    import xml.etree.ElementTree as ET

    theme_dir = os.path.dirname(qrc_file)

    try:
        tree   = ET.parse(qrc_file)
        root   = tree.getroot()
        prefix = root.find("qresource").get("prefix", "/")
        files  = [f.text.strip() for f in root.iter("file")]
    except Exception as e:
        print(f"[style_loader] Gagal parse {qrc_file}: {e}")
        return

    lines = [
        "# AUTO-GENERATED by style_loader.py — jangan edit manual",
        "from PyQt6.QtCore import QDir",
        "from PyQt6.QtGui import QPixmap",
        "from PyQt6 import QtCore",
        "",
        "def _register():",
        f'    prefix = "{prefix}"',
        "    data = {",
    ]

    for fname in files:
        fpath = os.path.join(theme_dir, fname)
        if not os.path.isfile(fpath):
            print(f"[style_loader] File tidak ditemukan: {fpath}")
            continue
        with open(fpath, "rb") as f:
            b64 = base64.b64encode(f.read()).decode()
        lines.append(f'        "{fname}": "{b64}",')

    lines += [
        "    }",
        "    import base64",
        "    from PyQt6.QtCore import QByteArray",
        "    for name, b64 in data.items():",
        "        ba = QByteArray(base64.b64decode(b64))",
        f'        QtCore.QResource.registerResource(ba, f":/{{prefix}}/{{name}}")',
        "",
        "_register()",
    ]

    with open(rc_file, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"[style_loader] ✔ Generated {theme}_rc.py (base64 fallback)")


def _import_rc(theme: str, theme_dir: str):
    """Import <theme>_rc.py agar resource terdaftar ke Qt."""
    rc_file = os.path.join(theme_dir, f"{theme}_rc.py")
    if not os.path.isfile(rc_file):
        return

    if theme_dir not in sys.path:
        sys.path.insert(0, theme_dir)

    try:
        import importlib
        mod_name = f"{theme}_rc"
        if mod_name in sys.modules:
            importlib.reload(sys.modules[mod_name])
        else:
            importlib.import_module(mod_name)
    except Exception as e:
        print(f"[style_loader] Gagal import {theme}_rc: {e}")


def load_style(name: str) -> str:
    """
    Load file .qss berdasarkan nama theme dan register resource-nya.
    File dicari di: ui/css/<name>/<name>.qss

    Contoh:
        load_style("darkstyle")

    Return string QSS, atau string kosong jika file tidak ditemukan.
    """
    theme_dir = os.path.join(_CSS_DIR, name)
    qss_file  = os.path.join(theme_dir, f"{name}.qss")

    if not os.path.isfile(qss_file):
        print(f"[style_loader] File tidak ditemukan: {qss_file}")
        return ""

    _compile_and_register_qrc(name)

    with open(qss_file, "r", encoding="utf-8") as f:
        return f.read()